// Static application markup only. Chat and model content is always rendered as text.
export const shell = `
<header class="topbar"><a class="brand" href="/" aria-label="CatchUp home"><span class="brand-icon">✓</span> CatchUp<span class="brand-dot">•</span></a><div class="tagline">Back in the loop.<br><span>On your terms.</span></div><div class="features"><span>◈ Processed on your device</span><span>☷ Role-aware context</span><span>▤ Source verification</span></div><button id="clear" class="secondary">Clear session</button><button id="privacy-link" class="quiet">Privacy note</button></header>
<div class="privacy-strip">Imported chats and results stay in this browser session. Only preferences are saved if you choose.</div>
<aside class="navigation"><span class="eyebrow">YOUR WORKSPACE</span><nav><button data-view="import" class="nav-item active">＋ Import & configure</button><button data-view="workspace" class="nav-item">▤ Catch-up workspace</button><button data-view="privacy" class="nav-item">◈ Privacy & storage</button></nav><div class="nav-note"><strong id="runtime-label">Extractive mode available</strong><span>No chat upload endpoints.</span></div></aside>
<main><div id="status" role="status" aria-live="polite"></div>
<section id="import-view"><div class="page-heading"><div><span class="eyebrow">YOUR CONTEXT. YOUR PRIORITIES.</span><h1>Import & configuration</h1><p>Bring a conversation. Leave the noise behind.</p></div><span class="badge">◈ Local profile · No sign-in</span></div>
<div class="import-grid"><div><section class="panel"><div class="section-title"><span class="step">1</span><div><h2>Your local profile</h2><p>Tell CatchUp what matters to you.</p></div></div>
<form id="profile"><label>Your name in the chat<input id="name" maxlength="100" required placeholder="Match your chat display name" list="participants"><datalist id="participants"></datalist></label><p class="hint">Choose an imported participant or enter your display name.</p>
<label>Your role<select id="role"><option value="student">Student</option><option value="developer">Developer</option><option value="lead">Project lead</option><option value="custom">Custom</option></select></label>
<label>Interests & contextual filters<input id="interests" placeholder="Reviews, deadlines, project updates"></label><p class="hint">Separate interests with commas.</p>
<label>Your responsibilities<textarea id="responsibilities" maxlength="500" rows="3" placeholder="What are you responsible for?"></textarea></label><label>Summary detail<select id="length"><option value="brief">Brief · Just the essentials</option><option value="detailed">Detailed · More context</option></select></label>
<label class="check"><input id="remember" type="checkbox"> Remember preferences on this device</label><p class="hint">This saves your profile in browser storage. Chats are never saved here.</p><button type="submit" class="secondary full">Apply preferences</button></form><button id="forget" class="quiet">Forget saved profile</button></section>
<div class="guide"><h3>Before you import</h3><p>Export your WhatsApp conversation <strong>without media</strong>, then choose the .txt file. Unzip it first if needed.</p><p>Use a conversation you have permission to process. No account connection is required.</p></div></div>
<div class="import-right"><section class="panel"><div class="section-title"><span class="step">2</span><div><h2>Import your conversation</h2><p>WhatsApp exports or plain text from another app.</p></div></div>
<div class="row"><label>Source format<select id="format"><option value="whatsapp">WhatsApp (.txt)</option><option value="plain">Plain text / other app</option></select></label><label>Date order<select id="dateOrder"><option value="">Confirm if prompted</option><option value="DMY">Day / month / year</option><option value="MDY">Month / day / year</option></select></label></div>
<div id="drop-zone" class="upload"><span class="upload-icon">↥</span><strong>Drop a text export here or browse files</strong><span>Up to 2 MB · Read locally in your browser</span><input id="file" aria-label="Choose text export" type="file" accept=".txt,text/plain"><span id="file-name"></span></div>
<details class="paste-box" open><summary>Or paste a conversation</summary><label class="sr-only" for="chat">Conversation text</label><textarea id="chat" rows="5" placeholder="Paste the original text here…"></textarea></details><button id="parse" class="secondary">Preview import</button><div id="preview"></div>
<label>Catch up since <span class="hint">(optional · export time)</span><input id="since" type="datetime-local"></label><p class="hint">Plain text has no verified timestamps. Export times have no verified timezone.</p></section>
<section class="panel"><div class="section-title"><span class="step">3</span><div><h2>Choose your processing mode</h2><p>Both modes keep chat processing on your device.</p></div></div><div class="engine-grid"><div class="engine-card"><span class="badge">CONTEXTUAL AI</span><h3>On-device AI</h3><p>Understand decisions and actions in context with a local language model.</p><p class="hint">First use downloads large model files. Requires WebGPU and enough device memory.</p><button id="load" class="secondary">Enable local AI</button></div><div class="engine-card"><span class="badge">NO MODEL DOWNLOAD</span><h3>Relevant excerpts</h3><p>Original messages ranked by your name and interests. No inferred tasks or deadlines.</p><button id="extractive" class="secondary">Use extractive mode</button></div></div><p id="model-status" class="runtime" aria-live="polite">Extractive mode available now</p></section>
<div class="launch"><div><h2>Ready to catch up?</h2><p>Your sources stay one click away.</p></div><button id="summarize">Catch me up <span aria-hidden="true">→</span></button><button id="cancel" class="quiet" hidden>Cancel</button></div></div></div></section>
<section id="workspace-view" hidden><div class="page-heading"><div><span class="eyebrow">LESS SCROLLING. MORE CONTEXT.</span><h1>Your catch-up workspace</h1><p id="workspace-meta">Import a conversation to get started.</p></div><button id="configure" class="secondary">Edit context & import</button></div><div class="workspace-grid"><aside class="panel context-card"><span class="eyebrow">YOUR CONTEXT</span><h2 id="context-name">No profile yet</h2><p id="context-role"></p><p id="context-interests" class="hint"></p><button id="edit-profile" class="secondary full">Edit preferences</button><div class="guide"><strong>Verify every takeaway</strong><p>Open a citation to inspect the exact source. AI can miss context or make mistakes.</p></div></aside><section class="source-panel"><div class="source-heading"><h2>Conversation</h2><p id="source-count">No messages imported</p><label class="sr-only" for="source-search">Filter source messages</label><input id="source-search" placeholder="Filter by participant or keyword"></div><div id="source-feed" class="source-feed"><p class="empty">Your imported messages will appear here.</p></div><button id="more-sources" class="quiet full" hidden>Show more messages</button></section><section id="results" aria-live="polite"><div class="panel empty"><span class="empty-icon">▤</span><h2>A little less noise.</h2><p>Import a conversation and choose your context to create your first brief.</p></div></section></div></section>
<section id="privacy-view" hidden><div class="page-heading"><div><span class="eyebrow">PRIVACY BY DESIGN</span><h1>Your conversation stays here.</h1><p>A clear view of what is stored, processed, and downloaded.</p></div></div><div class="privacy-grid"><article class="panel"><h2>On this device</h2><p>Imported messages and generated results are held in browser memory. Parsing, ranking and AI inference run here.</p><p>Optional profiles are saved in localStorage, which is not encrypted by this app. A profile is personalization, not authentication.</p></article><article class="panel"><h2>Network connections</h2><p>The app loads from its host. Enabling AI fetches model files from artifact hosts, revealing ordinary connection metadata. No chat text is included in those requests.</p><p>There are no chat upload APIs, cloud inference fallbacks, or analytics in this app.</p></article><article class="panel"><h2>Clearing your session</h2><p>Clear session removes chat/results from the interface, releases app references and stops the model worker. Saved preferences and cached model files remain.</p><p>This is not a forensic memory wipe. It does not remove your original export file. Use Forget saved profile to remove saved preferences.</p></article><article class="panel"><h2>Know the limits</h2><p>Source validation checks that references exist; it does not prove every AI claim. Review the original conversation before acting.</p><p>Imports may contain sensitive messages. Use permissioned data and avoid shared unlocked devices.</p></article></div></section>
<footer>CatchUp · Back in the loop. On your terms.<span>Local profiles, not authenticated accounts.</span></footer></main>`;
